"""Add question tracking and effectiveness

Revision ID: 41cbaa92e74e
Revises: 0d252373b0d1
Create Date: 2026-06-19 22:25:28.862976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41cbaa92e74e'
down_revision: Union[str, Sequence[str], None] = '0d252373b0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_effectiveness',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.String(length=255), nullable=False),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=4), server_default='0.0', nullable=False),
    sa.Column('average_score', sa.Numeric(precision=5, scale=4), server_default='0.0', nullable=False),
    sa.Column('average_latency', sa.Numeric(precision=6, scale=3), server_default='0.0', nullable=False),
    sa.Column('total_responses', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('question_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('question_id', sa.String(length=255), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('concept_id', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('candidate_answer', sa.Text(), nullable=True),
    sa.Column('mastery_outcome', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('latency', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_responses')
    op.drop_table('question_effectiveness')
    # ### end Alembic commands ###
