"""Add graph edge statistics table

Revision ID: 7034b511f904
Revises: 41cbaa92e74e
Create Date: 2026-06-20 20:53:15.919270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7034b511f904'
down_revision: Union[str, Sequence[str], None] = '41cbaa92e74e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_edge_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_concept', sa.String(length=255), nullable=False),
    sa.Column('target_concept', sa.String(length=255), nullable=False),
    sa.Column('edge_strength', sa.Numeric(precision=5, scale=4), server_default='0.0', nullable=False),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=4), server_default='0.0', nullable=False),
    sa.Column('failure_rate', sa.Numeric(precision=5, scale=4), server_default='0.0', nullable=False),
    sa.Column('traversal_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graph_edge_statistics')
    # ### end Alembic commands ###
