"""Initial schema

Revision ID: a6943b471431
Revises: 
Create Date: 2026-06-19 20:57:01.829151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6943b471431'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.String(length=255), nullable=False),
    sa.Column('concept_id', sa.String(length=255), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('mastery', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('matched_signals', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('missing_signals', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('reasoning', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('metadata', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.String(length=255), nullable=False),
    sa.Column('concept_id', sa.String(length=255), nullable=False),
    sa.Column('mastery', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domain_mastery',
    sa.Column('candidate_id', sa.String(length=255), nullable=False),
    sa.Column('domain_id', sa.String(length=255), nullable=False),
    sa.Column('mastery', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('candidate_id', 'domain_id')
    )
    op.create_table('graph_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.String(length=255), nullable=False),
    sa.Column('total_concepts', sa.Integer(), nullable=False),
    sa.Column('total_edges', sa.Integer(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('density', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id')
    )
    op.create_table('interview_sessions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('candidate_id', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('current_concept', sa.String(length=255), nullable=False),
    sa.Column('visited_concepts', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('mastery_history', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('success_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failure_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('accelerated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('terminated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.String(length=255), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=False),
    sa.Column('skills', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('education', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('projects', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id')
    )
    op.create_table('interview_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('concept_scores', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('domain_scores', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('strong_concepts', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('weak_concepts', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('recommended_topics', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_reports')
    op.drop_table('resume_data')
    op.drop_table('interview_sessions')
    op.drop_table('graph_statistics')
    op.drop_table('domain_mastery')
    op.drop_table('concept_progress')
    op.drop_table('concept_evaluations')
    # ### end Alembic commands ###
